/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package minorproject;

import java.sql.Connection;
import javax.swing.JFrame;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author adity
 */
public class AddStudent extends javax.swing.JFrame {

    /**
     * Creates new form test
     */
    
    
    public AddStudent() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        erpid = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        course = new javax.swing.JTextField();
        batch = new javax.swing.JTextField();
        number = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        submit = new javax.swing.JButton();
        discard = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        erpid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                erpidActionPerformed(evt);
            }
        });
        jPanel1.add(erpid, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 190, -1));

        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 190, -1));
        jPanel1.add(course, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 190, -1));
        jPanel1.add(batch, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 190, -1));
        jPanel1.add(number, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 190, -1));
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 190, -1));

        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        jPanel1.add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 400, -1, -1));

        discard.setText("Discard");
        discard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discardActionPerformed(evt);
            }
        });
        jPanel1.add(discard, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 440, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Student Register.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void erpidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_erpidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_erpidActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void discardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discardActionPerformed
        // TODO add your handling code here:
        this.dispose();
        JFrame StudentFrame = new StudentHome();
        new StudentHome().setVisible(true);
    }//GEN-LAST:event_discardActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
         Connection conn = null;
    PreparedStatement pstmt = null;
    ResultSet resultSet = null;

    try {
        // Establish a database connection
        conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/crc", "root", "1702");

        // Retrieve data from GUI components
        String stderpid = erpid.getText();
        String stdname = name.getText();
        String stdcourse = course.getText();
        String stdbatch = batch.getText();
        String stdnumberStr = number.getText();
        String stdemailAddress = email.getText();

        if (stderpid.isEmpty() || stdname.isEmpty() || stdcourse.isEmpty() || stdbatch.isEmpty() || stdnumberStr.isEmpty() || stdemailAddress.isEmpty()) {
            JOptionPane.showMessageDialog(null, "All fields are required.");
        } else if (!stdnumberStr.matches("\\d{10}")) {
            JOptionPane.showMessageDialog(null, "MobileNumber must be a 10-digit number.");
        } else {
            // Check if ERPID or Mobile number already exists in the database
            String checkQuery = "SELECT COUNT(*) FROM Student WHERE ERPID = ? OR MobileNumber = ?";
            pstmt = conn.prepareStatement(checkQuery);
            pstmt.setString(1, stderpid);
            pstmt.setString(2, stdnumberStr);
            resultSet = pstmt.executeQuery();
            resultSet.next();
            int count = resultSet.getInt(1);

            if (count > 0) {
                JOptionPane.showMessageDialog(null, "ERPID or MobileNumber already exists in the database.");
            } else {
                // Convert the MobileNumber to a long
                long stdnumber = Long.parseLong(stdnumberStr);

                // Create an SQL INSERT statement
                String sql = "INSERT INTO Student (ERPID, Name, Course, Batch, MobileNumber, EmailAddress) VALUES (?, ?, ?, ?, ?, ?)";
                pstmt = conn.prepareStatement(sql);

                // Set the parameter values
                pstmt.setString(1, stderpid);
                pstmt.setString(2, stdname);
                pstmt.setString(3, stdcourse);
                pstmt.setString(4, stdbatch);
                pstmt.setLong(5, stdnumber);
                pstmt.setString(6, stdemailAddress);

                // Execute the INSERT statement
                pstmt.executeUpdate();

                // Inform the user that the data has been successfully inserted
                JOptionPane.showMessageDialog(null, "Data has been inserted into the Student table.");
                
                this.dispose();
                JFrame StudentFrame = new StudentHome();
                new StudentHome().setVisible(true);
            }
        }

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
    } finally {
        try {
            if (resultSet != null) {
                resultSet.close();
            }
            if (pstmt != null) {
                pstmt.close();
            }
            if (conn != null) {
                conn.close();
            }
        } catch (SQLException e) {
            // Handle any cleanup operations
        }
    }
    }//GEN-LAST:event_submitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField batch;
    private javax.swing.JTextField course;
    private javax.swing.JButton discard;
    private javax.swing.JTextField email;
    private javax.swing.JTextField erpid;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField name;
    private javax.swing.JTextField number;
    private javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables
}
